image: debian/stretch
packages:
  - git
  - openjdk-8-jdk-headless
  - wget
  - tar
  - unzip
  - lib32stdc++6
  - lib32z1
  - file
  - mesa-utils
  - pciutils
environment:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  GRADLE_USER_HOME: "/home/build/.gradle"
  ANDROID_HOME: "/home/build/.androidhome"
  ANDROID_EMULATOR_SDK: "28"
sources:
  - https://git.sr.ht/~cowboyprogrammer/feeder
tasks:
 - setup: |
     export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
     env
     cd feeder
     echo 'org.gradle.jvmargs=-Xmx1g' >> gradle.properties
     ci/before
 - build: |
     cd feeder
     ./gradlew build
