pipeline:
  build-server:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install --upgrade -r server/flaskapp/requirements.txt
      #- pip install -e server/flaskapp

matrix:
  PYTHON_VERSION:
    - 3.4
    - 3.5
    - 3.6
