"project_id": "433800"
"api_token": "CROWDIN_PERSONAL_TOKEN"
"base_path": "/"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"commit_message": "New {languageName} translations from Crowdin"

"files": [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "translation": "/app/src/main/res/values-%android_code%/%original_file_name%"
  }
]
