base_path: /
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    update_option: update_without_changes
  - source: fastlane/metadata/android/en-US/full_description.txt
    translation: fastlane/metadata/android/%locale%/%original_file_name%
